### ISSUE TITLE
Author name is not appearing 

### ISSUE THREAD

**Issue by webofbits** [pch/wellspring-example-blog#1]
the author name is saved like nil in the database.

**Comment by webofbits** [comment]
I found a way to fix this: 

```
def entry_params
      allowed_attrs = %i(id type title slug published_at)
        .concat(content_class.constantize.content_attributes.keys)

      params.require(:entry).permit(*allowed_attrs)
    end
```
as you can see there's no author_name inside allowed_attrs. Putting it right there the author name is salved in the database.
p.s. I know this is not a problem in the blog. the place you need to change is inside the wellspring plugin.

**Comment by pch** [comment]
https://github.com/pch/wellspring/commit/e667a6e8f2739edb4940c288a6d210525a7ae791
