### ISSUE TITLE
'invalid gemspecs' error

### ISSUE THREAD

**Issue by mvasin** [pch/wellspring-example-blog#2]
I get this error upon `bundle`:

```
Fetching dependency metadata from https://rubygems.org/
Fetching git://github.com/pch/wellspring.git
You have one or more invalid gemspecs that need to be fixed.
The gemspec at
/Users/xxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/wellspring-9f558757db57/wellspring.gemspec
is not valid. Please fix this gemspec.
The validation error was '"FIXME" or "TODO" is not a description
```

**Comment by Quinncuatro** [comment]
You just have to change them to anything  that's not "FIXME" or "TODO". The homepage needs to be a URI, though.

**Comment by pch** [comment]
Yeah, newer versions of rubygems throw an error when you leave default strings in .gemspec. This should solve it: https://github.com/pch/wellspring/commit/04f0ca2cfe48423bdacef90ad4103fc1b2202194
